#Minecraft server properties
#Tue Mar 24 15:22:51 GMT 2026
allow-flight=false
allow-nether=true
default-gamemode=0
level-name=world
level-seed=
max-players=20
online-mode=false
pvp=true
server-ip=
server-port=25565
spawn-animals=true
spawn-monsters=true
view-distance=10
white-list=false
